services:

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DBNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DATABASE/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./API/.env.prod
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: